name: Build Jekyll and Deploy to _site Branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # 1. 检出主分支代码
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # 2. 检查 _site 分支是否存在
      - name: Check if _site branch exists
        id: check-branch
        run: |
          if git ls-remote --exit-code --heads origin _site; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          fi

      # 3. 如果分支不存在，创建空的 _site 分支
      - name: Create _site branch if needed
        if: steps.check-branch.outputs.branch_exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan _site
          git rm -rf . || true
          echo "# Empty _site branch" > README.md
          git add README.md
          git commit -m "Initial commit for _site branch"
          git push origin _site
          git checkout main

      # 4. 设置 Ruby 环境
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true

      # 5. 安装依赖并构建Jekyll站点
      - name: Build with Jekyll
        run: |
          bundle install
          bundle exec jekyll build

      # 6. 部署生成的_site内容到_site分支
      - name: Deploy to _site branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: _site  # 修正参数名
          keep_files: false
          force_orphan: true